#161255322 Pagination support for articles
andela/ah-codeofduty-frontend pull request #16
Opened 2018-12-11 15:59 UTC by njeri-ngigi

#### What does this PR do?
- Adds a pagination component for articles
- Adds tests for this component
#### Description of tasks to be completed
> Pagination support for articles

**Why this is important**
- Add pagination to our articles to make article traversal easier.

#### Relevant PT stories
[Pagination support for articles](https://www.pivotaltracker.com/story/show/161255322)

#### Screenshots:
![image](https://user-images.githubusercontent.com/28973383/49812564-bfc30f00-fd76-11e8-89b2-81dc645e45df.png)
![image](https://user-images.githubusercontent.com/28973383/49812583-c3ef2c80-fd76-11e8-9172-33237f339681.png)

2018-12-15 21:23 UTC, AnguleMathias requested changes
Great work implementing the functionality but test coverage on the PR is 26.6% (50% is the threshold) thereby a negative deviation in relation to the develop branch. Work on improving the test coverage

2018-12-17 08:53 UTC, maxwellgithinji approved these changes
LGTM

2018-12-17 08:54 UTC, AnguleMathias approved these changes
Great work

2018-12-17 08:54 UTC, KITHU approved these changes

2018-12-17 08:54 UTC, merged