#161255325  Article tags should be present in all relevant views
andela/ah-codeofduty-frontend pull request #17
Opened 2018-12-13 14:46 UTC by njeri-ngigi

#### What does this PR do?
- Adds a tagging component that can be passed to any view 
- Adds tests for this component
#### Description of tasks to be completed
>  Article tags should be present in all relevant views

**Why this is important**
Tagging refers to the metadata that is assigned to a piece of content by the content creator and the readers/users of the content. Tagging allows for organization and or categorization of content

**As a User**
I want to be able to view various article tags to enable easy filtering and navigation to articles of interest 

**Acceptance Criteria**
Scenario:
Only **authenticated** users should be able to tag articles .

#### Relevant PT stories
[Article tags should be present in all relevant views](https://www.pivotaltracker.com/story/show/161255325)

#### Screenshots:
![image](https://user-images.githubusercontent.com/28973383/49945926-f0ce4b80-fefe-11e8-9b92-0b41c0529d7a.png)

2018-12-15 21:25 UTC, AnguleMathias requested changes
Good work on feature implementation. Work on fixing code climate issue and improve on test coverage.

2018-12-17 12:26 UTC, 3N61N33R approved these changes

2018-12-18 14:32 UTC, AnguleMathias approved these changes

2018-12-19 09:32 UTC, KITHU requested changes
kindly remove complexity: hint reduce number of lines in your render method

2018-12-19 13:21 UTC, KITHU approved these changes

2019-01-02 08:19 UTC, merged